import { bold, cyan, dim, green, yellow, red } from "../lib/colors";
import { existsSync } from "fs";
import { appendFile, readFile } from "fs/promises";

const SHELL_FUNCTION = `
# wte CLI wrapper (auto-generated by wte init)
wte() {
  local cdfile="/tmp/.wte_cd_\$\$"
  __WT_CD_FILE__="$cdfile" command wte "$@"
  local rc=$?
  if [[ -f "$cdfile" ]]; then
    local target=$(cat "$cdfile")
    rm -f "$cdfile"
    cd "$target"
  fi
  return $rc
}
`;

export default async function init(args: string[]) {
  const install = args.includes("--install");

  console.log(bold("\nwte init\n"));
  console.log("Shell wrapper function for wte CLI:");
  console.log(dim("(Enables `wte go` / `wte create` to cd into worktrees)\n"));
  console.log(cyan(SHELL_FUNCTION));

  if (!install) {
    console.log(dim("To auto-install, run:"));
    console.log(bold("  wte init --install\n"));
    console.log(dim("Or manually add the above to your shell rc file."));
    return;
  }

  // Determine rc file
  const shell = process.env.SHELL || "";
  const home = process.env.HOME || "";
  const rcFile = shell.includes("zsh") ? `${home}/.zshrc` : `${home}/.bashrc`;

  // Check if already installed
  try {
    const content = await readFile(rcFile, "utf-8");
    if (content.includes("__WT_CD__") || content.includes("__WT_CD_FILE__")) {
      console.log(yellow(`  ⚠ Shell function already exists in ${rcFile}`));
      return;
    }
  } catch {
    // File might not exist, that's ok
  }

  try {
    await appendFile(rcFile, SHELL_FUNCTION);
    console.log(green(`  ✓ Added to ${rcFile}`));
    console.log(dim(`  Run: source ${rcFile}`));
  } catch (err) {
    console.error(red(`  ✗ Failed to write to ${rcFile}: ${err}`));
    process.exit(1);
  }

  console.log();
}
